### ISSUE TITLE
aria2/curl selection setting doesn't take effect

### ISSUE THREAD

**Issue by ifoolb** [e-alfred/ocdownloader#72]
### Steps to reproduce
1. select curl under additional settings ocdownloader section
2. navigate to ocdownloader it still says "using ARIA2"
3.

### Expected behaviour
using CURL instead
### Actual behaviour
still using aria2 to do downloads
### Server configuration

**Operating system**:
CentOS 7
**Web server:**
Apache 2.4
**Database:**
Sqlite, in which I have:
sqlite> select * from oc_ocdownloader_adminsettings;
1|AllowProtocolBT|N
2|WhichDownloader|CURL

**PHP version:**
php 71w
**Nextcloud version:** (see Nextcloud admin page)
13
**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh install, only did chmod +x fallback.*, without touching anything else
**Where did you install Nextcloud from:**
official tarball

**Comment by e-alfred** [comment]
Does the setting work if you change it in the SQLite database by hand? Otherwise I am not too confident to support a DBMS that isn't even really supported by Nextcloud:

https://docs.nextcloud.com/server/13/admin_manual/configuration_database/linux_database_configuration.html

**Comment by ifoolb** [comment]
I suppose not, because when I open the database, I find duplicate rows in it, such as
2|WhichDownloader|CURL
3|WhichDownloader|ARIA2
4|WhichDownloader|CURL
After switching to MariaDB the settings work well, so it does seem to be a problem because of SQLite.
But SQLite is convenient, if it's supported then I won't need to run another daemon on my 'micro' server.

**Comment by e-alfred** [comment]
This will probably be solved by https://github.com/e-alfred/ocdownloader/issues/73. Rework will take some time probably, but if you want to help out pull requests are always welcome.

**Comment by DocSniper** [comment]
I've updated to 1.6.1 but still having the same problem.

DB is sqlite, I've set the execute permissions for the fallback and I have selected cURL as downloader in the setting.

I had the same DB problem as @ifoolb and used the following commands to correct it:
delete from oc_ocdownloader_adminsettings where id = X;
insert into oc_ocdownloader_adminsettings values (1,'AllowProtocolBT','N');
insert into oc_ocdownloader_adminsettings values (2,'WhichDownloader','CURL');

to this:
1 | AllowProtocolBT | N
2 | whichDownloader | CURL

However, the problem still exists with the new version 1.6.1

**Comment by DocSniper** [comment]
Here a quick solution to use curl instead of aria2:

In the file `apps/ocdownloader/controller/libs/settings.php` add in the function `public function getValue()` as first line after the `{`  this new line: `if ($this->Key == 'WhichDownloader') return 'CURL';`

Don't forget to adjust the path to the youtube-dl binary `$this->YTDLBinary = '/usr/local/bin/youtube-dl'; // default path` in the file `apps/ocdownloader/controller/ytdownloader.php` (I had to delete `local`).

**Comment by e-alfred** [comment]
Nextcloud offically doesn't support SQLite anymore, this app cannot support things that aren't supported by Nextcloud directly, so only Mariadb/Mysql and Postgresql are supported for now: https://docs.nextcloud.com/server/18/admin_manual/configuration_database/linux_database_configuration.html
